name: tvr_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  phosphor_flutter: ^2.1.0
  font_awesome_flutter: ^10.8.0
  mobile_scanner: ^7.0.1
  video_player: ^2.10.0
  flutter_native_splash: ^2.4.6
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  confetti: ^0.8.0
  animated_text_kit: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/images/flash-icon.png"
    adaptive_icon_foreground: "assets/images/flash-icon.png"
    adaptive_icon_background: "#000000"  

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
  
  fonts:
    - family: Jura
      fonts:
        - asset: assets/fonts/Jura-Regular.ttf
  
