// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCge5jzcbAg7U9os6JGWcCV9-T5-kMTB7U',
    appId: '1:21385820263:web:798893377ce3826030fcc2',
    messagingSenderId: '21385820263',
    projectId: 'tvr-project',
    authDomain: 'tvr-project.firebaseapp.com',
    storageBucket: 'tvr-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFfIQHhpictREmOyPpQ1s-z17Bm7EkXuQ',
    appId: '1:21385820263:android:05010130590e598330fcc2',
    messagingSenderId: '21385820263',
    projectId: 'tvr-project',
    storageBucket: 'tvr-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM1jK-x-n1XW1FOF2sAvd1xObF9BEb8Is',
    appId: '1:21385820263:ios:8a14e83d486d91a030fcc2',
    messagingSenderId: '21385820263',
    projectId: 'tvr-project',
    storageBucket: 'tvr-project.firebasestorage.app',
    iosBundleId: 'com.example.tvrApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM1jK-x-n1XW1FOF2sAvd1xObF9BEb8Is',
    appId: '1:21385820263:ios:8a14e83d486d91a030fcc2',
    messagingSenderId: '21385820263',
    projectId: 'tvr-project',
    storageBucket: 'tvr-project.firebasestorage.app',
    iosBundleId: 'com.example.tvrApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCge5jzcbAg7U9os6JGWcCV9-T5-kMTB7U',
    appId: '1:21385820263:web:b00064370c46a7eb30fcc2',
    messagingSenderId: '21385820263',
    projectId: 'tvr-project',
    authDomain: 'tvr-project.firebaseapp.com',
    storageBucket: 'tvr-project.firebasestorage.app',
  );
}
